language: generic
env:
  matrix:
    - CI_TARGET=vim
    - CI_TARGET=neovim
before_script:
  - sudo apt-get update
  - sudo apt-get install python3-dev
  - if [ $CI_TARGET = vim ]; then
      sudo apt-get install vim-gnome;
    elif [ $CI_TARGET = neovim ]; then
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64" &&
      wget https://bootstrap.pypa.io/get-pip.py &&
      sudo python3 get-pip.py &&
      sudo pip3 install neovim;
    fi
  - wget https://github.com/google/vroom/releases/download/v0.13.0/vroom_0.13.0-1_all.deb
  - sudo dpkg -i ./vroom_0.13.0-1_all.deb
services:
  - xvfb
script:
  - '[ $CI_TARGET = neovim ] && VROOM_ARGS="--neovim" || VROOM_ARGS=""'
  - vroom $VROOM_ARGS --crawl --skip=vroom/system-vimjob.vroom
matrix:
  fast_finish: true
  allow_failures:
    - env: CI_TARGET=neovim
